### PR TITLE
REPLACEFILE don't error if file does not exist

### LINKED ISSUE #16: REPLACEFILE errors despite success
Hi, thanks for your updates to this handy tool.
I was just putting a simple cross-dev script together and this puzzled me a bit:

> cadius.exe v 1.4.0 (c) Brutal Deluxe 2011-2013.
>   - Replacing file '/MERLIN16/M2#061000' :
>   Error : Can't get file from Image, File not found.
>   Error : Invalid Prodos File path '/MERLIN16/M2'.

That's a REPLACEFILE when the destination file (M2) doesn't exist.
I haven't looked at the code yet but I presume the error is from the delete.
It actually adds the file and returns a success code, but it would be nicer without errors.

Cheers,
Nick.

### PR DESCRIPTION
**Pull request by mach-kernel**
- Resolves #16 
- Adds silent flag to `GetProdosFile()`, `DeleteProdosFile()`

### CODE REVIEW

**Comment by mach-kernel** [comment]
That's a great idea! I'll get on that and try to have it out soon. 👍

**Comment by sicklittlemonkey** [comment]
Have a look around at some C logging APIs. E.g. just did a quick google and found this - not necessarily to use, but perhaps a good example of a simple logging API:
https://github.com/rxi/log.c

**Comment by mach-kernel** [comment]
I made a small delegator to `vprintf` and a macro. In the future we can probably make levels but IMO doesn't need it. I was playing around in my head with adding something to manage the number of spaces/tabs prefixed to the output so that they wouldn't have to be prepended in the strings passed to the logger.

**Comment by sicklittlemonkey** [comment]
Nice! I like it. I see what you mean about the indentations. Tedious ...

The nice thing about log levels is differentiating between errors and other info. For instance when I now ask if you could squeeze in a -quiet (no logging (except errors?)) option into this release. ; - )

**Comment by mach-kernel** [comment]
@sicklittlemonkey will try to get this out by the end of the week. Haven't forgotten, work has been picking up. 🙈

**Comment by sicklittlemonkey** [comment]
It's a lot of work.

Probably better to split this out to another issue and release the REPLACEFILE fix etc.

**Comment by mach-kernel** [comment]
I added support for quiet and cleaned up how we're parsing the flags. I think that barring any tweaks / bugs discovered this should cover it. 😸

**Pull request merged**
