### PR TITLE
File type & auxtype in filename

### LINKED ISSUE #4: Better filetype & auxtype support
Ideally retain filetype & auxtype between Mac OS files & ProDOS

And/or allow explicit filetype and auxtype suffix:
PRODOS#FF0000
BIN.AT.2000#062000

-JB
@JBrooksBSI

### PR DESCRIPTION
**Pull request by mach-kernel**
Resolves #4!

WIP

### CODE REVIEW

**Comment by mach-kernel** [comment]
@JohnMBrooks would you be so kind as to give this a test before I merge it? You should just be able to pull and build. 🦄

**Comment by JohnMBrooks** [comment]
A quick review of the changes looks reasonable, but it is not working when tested by adding "BASIC.SYSTEM!FF0000" to a disk image.

1.3 created a file entry with the correct name bytes and filetype, but the storage type was set to 3 instead of 2 and the name length was 3 instead of $C. If I use cadius 1.3 without the metadata suffix of !FF0000, the file BASIC.SYSTEM is created correctly with a storagetype+len byte of $2C.

Other thoughts:
1) Why is the '!' character used? Is the standard syntax for type/auxtype '#'?

In shell scripts I need to escape the ! character in filenames.

2) My build scripts use cadius to delete the target file from the disk image, then add the newly built file. Will cadius deletefile of BASIC.SYSTEM!FF0000 correctly delete BASIC.SYSTEM from the disk image?

3) At least on MacOS, Apple used a convention of having HFS file type $70xxyyyy hold ProDOS meta data where xx is filetype & yy is auxtype. I'm not sure if this convention would still work with current versions of MacOS, but it would be a nice alternative to the suffix metadata in some situations.

4) BTW: There were a lot of compiler warnings when building cadius 1.3.

Hope that helps.
-JB

**Comment by mach-kernel** [comment]
@JohnMBrooks thanks for testing! I'll have to look into the name / storagetype issue...I am likely mishandling a string somewhere. 

As for questions,

1. I think I did my research incorrectly here, for some reason I believed that `#` was a reserved path character but [I can't confirm that from this MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions). I will switch to the `#`, but let me know if this rings any bells to you (my memory is bad 🤦‍♂️ )

2. You can invoke `DELETEFILE` with the filename not including the suffix (i.e. as returned by the `CATALOG` command) and it will do the deletion. Do you think it would make sense to extend this to also support receiving a filename with suffix? It should be easy to do this. 

3. I can try shoving it into `S_IFMT`? [stat.h doc](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/stat.2.html)

4. I will see what I can do to help knock those down: probably should start with the `printf` interpolation type mismatches. 

Let me know what you think! 😸

**Comment by JohnMBrooks** [comment]
1. See CiderPress tutorial doc:
http://apple2online.com/web_documents/ciderpress_tutorial.pdf
" sample.text#04000
The junk starting with "#" that was added to the filename is a file attribute preservation sequence. The first two digits are the ProDOS file type, the next four are the ProDOS aux type."

2. Yes, it would be preferable to allow scripts/vars to use the same name (with metadata) for delete as used for add. Another nice option would be a 'replace' cmd or option to add, which would do a delete followed by add instead of current system which requires 2x calls to cadius to update a file (delete followed by add).

3. The MPW LinkIIGS tool will put the filetype & auxtype into the output HFS file type. From "MPW IIgs Tools.pdf":

• The auxtype of the ouput file can be set using the new -at option. The format for this option is: -at Sxxxx where xxxx is the desired auxtype. Decimal numbers may also be used if the $ is left off.
The -t option has been changed to work more naturally with the new -at option. The syntax is now -t Sxx where xx is the desired Load File type. A decimal value can be used if the $ is left off. 

Several mnemonics are now recognized and will be convened to their corresponding file type. These mneomics are: S16, EXE, RTL, NDA, CDA, PIF, TIF, and TOL. If the output Load File type is set to RTL, the Load File will be converted to a Run Time Library.
• The combination of '-t' and '-at' allow both a file type and auxtype to be assigned at link time.
• LinklIGS now recognizes input files whose file type follows the 'pXYY' convention as well as the
standard Bx 'convention.

4. Several are new warnings due to filetype/auxtype sscanf mismatching uint* with ulong*.

-JB

**Comment by JohnMBrooks** [comment]
Confirmed sscanf warnings are fixed.
Confirmed # token works (much nicer than ! too).

Still get inorrect storage+len byte of $33 when copying BASIC.system#FF0000 to an image.

-JB

**Comment by mach-kernel** [comment]
@JohnMBrooks Thank you so much for continuing to validate this! :+1:

The DELETEFILE path feature + REPLACE command are coming in a few commits + still need to find the root of that storage+len byte issue :coffee:

**Comment by JohnMBrooks** [comment]
Confirmed storage+namelen bug fixed.
Confirmed correct filetype of SYS using metadata suffix #FF0000.

Looks good to merge.

-JB

**Comment by mach-kernel** [comment]
@JohnMBrooks I added the `REPLACEFILE` command. I'll add the HFS metadata support in another PR because I have to do some more piping for that. 

Also: would block device support be a desired feature? I'd love to use `cadius` to write directly to the CF card but I dunno if something else exists to do this.

**Comment by JohnMBrooks** [comment]
Yes, block device support would be super-useful. I have a RAMFast D SCSI connected to a SCSI2SD controller that contains a 2GB pSLC micro-SD card, formatted with 12 partitions:

sudo diskutil partitiondisk /dev/rdisk1 13 APM %Apple_PRODOS% PART1 65536S %Apple_PRODOS% PART2 65536S %Apple_PRODOS% PART3 65536S %Apple_PRODOS% PART4 65536S %Apple_PRODOS% PART5 65536S %Apple_PRODOS% PART6 65536S %Apple_PRODOS% PART7 65536S %Apple_PRODOS% PART8 65536S %Apple_PRODOS% PART9 65536S %Apple_PRODOS% PART10 65536S %Apple_PRODOS% PART11 65536S MS-DOS HFS1 3473000S "Free Space" FREE R
Note: In RAMFast.system, expand last partition to max (2GB), then format as HFS in GS Adv Disk Util or GS Finder

It is currently a pain to move files on & off the SD card partitions, since I have to use dd to extract the partition I want from the SD card onto a .PO disk image, then use cadius to move files to/from the .PO image, then migrate the partition back to the SD card with dd.

Because it's currently difficult (and kind of dangerous & high-wear on the SD flash card), I currently use CFFA 3000 or my xHD 230k serial disk image utility to migrate files onto the SD card using ProDOS.

-JB

**Comment by mach-kernel** [comment]
@JohnMBrooks looks like another feature, then 😄 

I'll merge this shortly, just try out `DELETEFILE` with the suffix and `REPLACEFILE` when you have a chance. 🚀

**Pull request merged**
